pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import AnswerForm
from ..models import Question, Answer
# from pybo import db
# from pybo.models import Question, Answer

# 3-08 모델 수정하기 @login_required 적용하기
from .auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')

#답변 등록은 POST요청만 있으므로 GET, POST 분기처리는 필요 없음.
@bp.route('/create/<int:question_id>', methods=('POST',))
# 3-08 모델 수정하기 @login_required 적용하기
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        # 템플릿의 form 엘리먼트를 통해 전달된 데이터들은 create 함수에서 request 객체로 얻을 수 있다.
        # request.form['content'] 코드는 POST 폼 방식으로 전송된 데이터 항복 중 name 속성이 content인 값을 의미한다.
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        # g.user는 세션에 저장된 사용자 정보 데이터이다. g.user는 auth_view.py 파일의 @bp.before_app_request 애너테이션에 의해 생성된다.
        question.answer_set.append(answer)
        # question.answer_set은 "질문에 달린 답변들"을 의미한다.
        # Question과 Answer 모델이 연결되어 있어 backref에 설정한 answer_set을 사용할 수 있음.
        db.session.commit()
        # return redirect(url_for('question.detail', question_id=question_id))
        # 3-12 앵커로 이동
        return redirect('{}#answer_{}'.format(
            url_for('question.detail', question_id=question_id), answer.id))

    return render_template('question/question_detail.html', question=question, form=form)

# 3-10 답변 수정 라우팅 함수
@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            # return redirect(url_for('question.detail', question_id=answer.question.id))
            # 3-12 앵커로 이동
            return redirect('{}#answer_{}'.format(
                url_for('question.detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)

# 3-10 답변 삭제 라우팅 함수
@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

# 3-11 답변 추천 라우팅 함수
@bp.route('/vote/<int:answer_id>/')
@login_required
def vote(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user == answer.user:
        flash('본인이 작성한 글은 추천할 수 없습니다')
    else:
        answer.voter.append(g.user)
        db.session.commit()
    # return redirect(url_for('question.detail', question_id=_answer.question.id))
    # 3-12 앵커로 이동
    return redirect('{}#answer_{}'.format(
                url_for('question.detail', question_id=answer.question.id), answer.id))

pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from .. import db
from ..models import Question, Answer, User
from ..forms import QuestionForm, AnswerForm
# from pybo.models import Question
# from pybo.forms import QuestionForm

# 3-08 모델 수정하기 @login_required 적용하기
from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')

# 3-14 검색 함수 (_list() 수정)
@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    question_list = Question.query.order_by(Question.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        question_list = question_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(Question.subject.ilike(search) |  # 질문제목
                    Question.content.ilike(search) |  # 질문내용
                    User.username.ilike(search) |  # 질문작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()
    question_list = question_list.paginate(page=page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)

# @bp.route('/list/')
# def _list():
#     # 페이지 적용
#     page = request.args.get('page', type=int, default=1) # 페이지
#     # GET 방식으로 요청한 URL에서 page값을 가져올 때 사용.
#     # list는 파이썬의 예약어이기 때문에 함수명을 _list로 지정.
#     question_list = Question.query.order_by(Question.create_date.desc())
#     question_list = question_list.paginate(page=page, per_page=10)
#     # paginate 함수의 첫번 째 인수로 전달된 page : 현재 조회할 페이지의 번호, 두번 째 인수 per_page : 페이지마다 보여 줄 게시물이 10건임.
#     return render_template('question/question_list.html', question_list=question_list)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)
# 질문 상세 템플릿에 폼이 추가되었으므로 question_views.py 파일의 detail 함수도 폼을 사용하도록 수정해야 함.
# 이 과정이 없으면 템플릿에서 form 객체를 읽지 못해 오류 발생.

@bp.route('/create/', methods=('GET', 'POST'))
# 3-08 모델 수정하기 @login_required 적용하기
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        # form.validate_in_submit 함수 : 전송된 폼 데이터의 정합성을 점검.
        #   즉, QuestionForm 클래스의 각 속성에 지정한 DataRequired() 같은 점검 항목에 이상이 없는지 확인함.
        # -> POST 요청, 폼 데이터에 이상이 없을 경우 질문을 저장한 뒤 main.index 페이지로 이동하라.
        question = Question(subject=form.subject.data, content=form.content.data,
                            create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)
# question_form.html 템플릿에 전달하는 QuestionForm의 객체(form)는 템플릿에서 라벨이나 입력폼 등을 만들때 필요함.

# 3-10 질문 수정 라우팅 함수
@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        # 만약 로그인한 사용자와 질문의 작성자가 다르면 수정할 수 없도록 flash 오류 발생.
        # flash 함수는 강제로 오류를 발생시키는 함수로, 로직에 오류가 있을 경우 사용한다.
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

# 3-10 질문 삭제 라우팅 함수
@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

# 3-11 질문 추천 라우팅 함수
@bp.route('/vote/<int:question_id>/')
@login_required
def vote(question_id):
    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user:
        flash('본인이 작성한 글은 추천할 수 없습니다.')
    else:
        _question.voter.append(g.user)
        # Question 모델의 voter는 여러 사람이 추가할 수 있는 다대다 관계이므로 _question.voter.append(g.user)와 같이 append 함수로 추천인을 추가해야 한다.
        # question_voter 테이블의 구조상 같은 사용자가 같은 질문을 여러 번 추천해도 추천 횟수는 증가하지 않는다.
        # 동일한 사용자를 append 할 때 오류가 날 것 같지만 내부적으로 중복되지 않도록 잘 처리된다.
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/templates/question/question_detail.html
<!--<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">-->
{% extends 'base.html' %}   <!--base.html 상속 받음.-->
{% block content %}

<div class="container my-3">
    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}

    <!-- 질문 -->
    <h2 class = "border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <!--style 삭제 후 markdown 필터 적용 -> markdown 적용 안돼서 삭제함 -->
            <div class="d-flex justify-content-end">
                <!--수정일시 표시하기-->
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.user.username }}</div>
                    <div>{{ question.create_date|datetime }}</div>
                </div>
            </div>
            <div class="my-3">
                <!--질문 추천 버튼 만들기-->
                <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}"
                    class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ question.voter|length }}</span>
                </a>
                {% if g.user == question.user %}
                <!--로그인한 사용자와 글쓴이가 같은 경우에만 수정 버튼이 보임.-->
                <!--질문 수정 버튼 추가-->
                <a href="{{ url_for('question.modify', question_id=question.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
                {% endif %}
             </div>
        </div><!--end card-body-->
    </div><!--end card-->

    <!-- 답변 목록-->
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }} 개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <!--3-12 앵커 엘리먼트-->
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <!--style 삭제 후 markdown 필터 적용 -> markdown 적용 안돼서 삭제함-->
            <div class="d-flex justify-content-end">
                <!--수정일시 표시하기-->
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.user.username }}</div>
                    <div>{{ answer.create_date|datetime }}</div>
                </div>
            </div>
            <div class="my-3">
                <!--답변 추천 버튼 만들기-->
                <a href="javascript:void(0)" data-uri="{{ url_for('answer.vote', answer_id=answer.id) }}"
                    class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ answer.voter|length }}</span>
                </a>
                {% if g.user == answer.user %}
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                {% endif %}
            </div>
        </div><!--end card-body-->
    </div><!--end card-->
    {% endfor %}

    <!--답변 등록 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        <!-- CSRF 토큰과 오류 표시 기능 -->
        {{ form.csrf_token }}

        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="mb-3">
            <!--3-08 로그아웃 상태에서 답변 등록 불가능하게 만들기-->
            <textarea {% if not g.user %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>

</div><!--end container-->
{% endblock %}

{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 질문 등록 -->
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <form method="post" class="my-3">
    <!-- CSRF 토큰 오류 처리 -->
    {{ form.csrf_token }}

    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field, errors in form.errors.items() %}
      <strong>{{ form[field].label }}</strong>
      <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endfor %}
    </div>
    {% endif %}
    <!--오류표시 End -->

    <div class="form-group">

      <div class="mb-3">
        <label for="subject">제목</label>
        <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
        <!-- subject 필드의 value값으로 {{ form.subject.data or '' }}를 입력하면 이미 전송한 데이터가 다시 설정됨.
              or ''은 "현재 템플릿이 GET 방식으로 요청되는 경우 기존 입력값이 없으므로(None으로 출력) 이를 방지하기 위해서" 사용.
              즉, form.subject.data에 값이 없을 때 None이 아니라 ''이 출력됨. -->
      </div>
      <div class="mb-3">
        <label for="content">내용</label>
        <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
      </div>

      <!--
      {{ form.subject.label }}  라벨
      {{ form.subject(class="form-control") }}      입력폼

      {{ form.content.label }}
      {{ form.content(class="form-control") }}
      -->

      <button type="submit" class="btn btn-primary">저장하기</button>

    </div>

  </form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
<!--<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">-->
{% extends 'base.html' %}   <!--base.html 상속 받음.-->
{% block content %}

<div class="container my-3">
    <!--3-14 검색 창-->
    <div class="row my-3">
        <div class="col-6">
            <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <!--자바 스크립트에서 이 텍스트창에 입력된 값을 읽기 위해 id(search_kw) 속성을 추가함.-->
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div><!--end col-->
    </div><!--end row-->

    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        <!-- 질문 목록 -->
        {% if question_list %}
        <!--render_template 함수에서 전달받은 질문 목록 데이터 question_list가 있는지 검사-->
        {% for question in question_list.items %}
        <!--question_list에 저장된 데이터를 하나씩 꺼내 question 객체에 대입한다. (파이썬의 for~in 문과 유사)-->
        <!--Pageination객체는 현재 조회된 목록데이터를 가져오기 위해서는 items 함수를 호출해야 함.-->

        <!--<li><a href="/detail/{{ question.id }}/">{{ question.subject }}</a></li>-->
            <!--바로 앞의 for 문에서 얻은 question 객체의 id를 출력. (question 객체의 subject를 출력)-->
        <tr class="text-center">
            <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
            <!--게시물 번호 공식을 질문 목록 템플릿에 적용.
                total : 전체 게시물 개수, page : 현재 페이지, per_page : 페이지당 게시물 개수, loop.index0 : 나열 인덱스(0부터 시작) -->
            <td class="text-start">
                <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                <!--기존에는 상세 페이지로 연결하는 링크가 /detail/{{ question.id }}/처럼 하드 코딩되어 있었음.
                    이 부분을 url_for 함수를 이용해 question.detail 라우팅 함수로 URL을 찾도록 변경함.
                    이때 question.detail 함수는 question_id 매개변수가 필요하므로 question_id를 전달해야 함.-->

                <!-- 질문에 달린 답변 개수 표시하기 -->
                {% if question.answer_set|length > 0 %}
                <!--답변이 있는 경우를 검사-->
                <span class="text-danger small mx-2">{{ question.answer_set|length }}</span>
                <!--답변 개수를 표시-->
                {% endif %}
            </td>
            <td>{{ question.user.username }}</td> <!--글쓴이 추가-->
            <td>{{ question.create_date|datetime }}</td>
            <!--파이프라인 문자와 함께 datetime 필터 적용. -> datetime필터가 적용되었으므로 format_datetime 필터 함수가 실행됨.
                이때 format_datetime의 매개변수 value에 question.create_date가 전달된다.-->
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

   <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">

        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <!--3-14 페이징 -> 기존의 페이징 처리 방식(?page=1) 변경. 검색과 페이징이 동시에 처리되려면 form을 통해 페이징이 요청되어야 함.
                                페이지 링크를 href 속성에 직접 입력하는 대신 data-page 속성으로 값을 읽을 수 있도록 변경.-->
            <a class="page-link" data-page="{{ question_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}

        <!-- 페이지번호 -->
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <!--3-14 페이징 -> 기존의 페이징 처리 방식(?page=1) 변경. 검색과 페이징이 동시에 처리되려면 form을 통해 페이징이 요청되어야 함.
                                페이지 링크를 href 속성에 직접 입력하는 대신 data-page 속성으로 값을 읽을 수 있도록 변경.-->
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
            <!--iter_pages 함수로 페이지가 나열될 때 페이지 번호(page_num)가 없는 경우 '...'을 표시 함.
                이는 보여 줄 페이지 번호가 지나치게 많은 경우 현재 페이지 위주로 보여주는 기술이다.-->
        </li>
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <!--3-14 페이징 -> 기존의 페이징 처리 방식(?page=1) 변경. 검색과 페이징이 동시에 처리되려면 form을 통해 페이징이 요청되어야 함.
                                페이지 링크를 href 속성에 직접 입력하는 대신 data-page 속성으로 값을 읽을 수 있도록 변경.-->
            <a class="page-link" data-page="{{ question_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

    <!--질문 등록 버튼 -> 검색창 좌측으로 이동 -->

</div>
<!--3-14 검색 폼 (page와 kw를 동시에 GET 방식으로 요청할 수 있는 form 엘리먼트 추가)-->
<form id="searchForm" method="get" action="{{ url_for('question._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}

<!--3-14 검색 스크립트 (페이징과 검색을 요청하는 자바스크립트 코드 추가)-->
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

<!--document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.-->